environment             = "ntt"
region                  = "sa-east-1"
profile                 = "notifications"
hosted_zone_id          = "Z08864533OKEN26MZ5PT9"
certificate_domain_name = "*.nttviewer.com"
keypair_name            = "notifier-backend-keypair"
